### ISSUE TITLE
carbon-c-relay 1.11: invalid free()

### ISSUE THREAD

**Issue by Civil** [grobian/carbon-c-relay#169]
When I'm trying to reload or quit(!) carbon-c-relay with a big config, I'm getting "invalid free()" on Linux machines.

Error:
```
*** glibc detected *** /usr/bin/carbon-c-relay: free(): invalid pointer: 0x0000000000669be0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75e66)[0x7f6077b5ae66]
/usr/bin/carbon-c-relay[0x414697]
/usr/bin/carbon-c-relay[0x4081f8]
/usr/bin/carbon-c-relay[0x410b7d]
/usr/bin/carbon-c-relay[0x4027a6]
/lib64/libc.so.6(+0x326a0)[0x7f6077b176a0]
/lib64/libc.so.6(nanosleep+0x2d)[0x7f6077b91a3d]
/lib64/libc.so.6(sleep+0xe0)[0x7f6077b918b0]
/usr/bin/carbon-c-relay[0x403c4a]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7f6077b03d5d]
/usr/bin/carbon-c-relay[0x402029]
```

Backtrace:
```
(gdb) bt full
#0  0x00007f6077b17625 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f6077b18e05 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f6077b55537 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007f6077b5ae66 in malloc_printerr () from /lib64/libc.so.6
No symbol table info available.
#4  0x0000000000414697 in server_free (s=0x66ed90) at server.c:626
No locals.
#5  0x00000000004081f8 in router_free_intern (clusters=0x66ecc0, routes=0x0) at router.c:176
        c = 0x66ecc0
        r = 0x0
        s = 0x678f80
        d = 0x0
        __PRETTY_FUNCTION__ = "router_free_intern"
#6  0x0000000000410b7d in router_free (rtr=0x61e110) at router.c:2343
No locals.
#7  0x00000000004027a6 in hup_handler (sig=1) at relay.c:218
        newrtr = 0xb086b0
        newaggrs = 0x0
        id = 21
        newfd = 0x5
        numaggregators = 0
#8  <signal handler called>
No symbol table info available.
#9  0x00007f6077b91a3d in nanosleep () from /lib64/libc.so.6
No symbol table info available.
#10 0x00007f6077b918b0 in sleep () from /lib64/libc.so.6
No symbol table info available.
#11 0x0000000000403c4a in main (argc=13, argv=0x7fff182d4ef8) at relay.c:689
        stream_sock = {3, 0, 0}
        stream_socklen = 1
        dgram_sock = {4, 0}
        dgram_socklen = 1
        id = 21 '\025'
        listenport = 2003
        listenbacklog = 1024
        ch = 1
        numaggregators = 0
        listeninterface = 0x0
        allowed_chars = 0x4195c5 "-_:#"
        smode = CUM
        pidfile = 0x0
        pidfile_handle = 0x0
        aggrs = 0x0
(gdb) frame 4
#4  0x0000000000414697 in server_free (s=0x66ed90) at server.c:626
626		free((char *)s->ip);
(gdb) info args
s = 0x66ed90
(gdb) p s
$1 = (server *) 0x66ed90
(gdb) p s->ip
$2 = 0xb792654 <Address 0xb792654 out of bounds>
```

**Comment by Civil** [comment]
Actually this doesn't happens on latest master, so looks like you've already fixed the issue. So the question is how far 1.12 from the release?

**Comment by Civil** [comment]
Backporting https://github.com/grobian/carbon-c-relay/commit/e4b6bf6748374da7fe9beeed906a20c3a9251dc4 that fixed this issue.
